# highlighter: pygments
highlighter: rouge

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: kramdown
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: https://kangkang0820.github.io/
devurl: http://localhost:4000/
name: kang
title: kangkang | As long as you live, so long will you struggle
description: "yukang's personal weblog, on coding or such stuff"

my:
    displayName: kangkang
    realName: YuKang
    realName_cn: 余康
    jobTitle: "psychology graduate student"
    contact:
        qq: 2500765857
        email: 2500765857@qq.com
        github: http://www.github.com/kangkang0820
        qzone: http://2500765857.qzone.qq.com
        address:
            country: China
            state: chongqing
            city: chongqing
            distribute: beibei

    skills:
        speciality: [“EEG data analysis”，“spss”,"R","Matlab","Python" ]


collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
